apiVersion : apps/v1
kind: Deployment
metadata:
  name: meghanapurimitla 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meghanapurimitla
  template:
    metadata:
      labels:
        app: meghanapurimitla 
    spec:
      containers:
        - name: meghanapurimitla 
          image: acraug.azurecr.io/meghanapurimitlaazuredeploy:latest
          ports:
          - containerPort: 8080
